In [38]:
import torch
import numpy as np

## Dot product of a 2d arrays

the input columns and multiplier output column size has to match

In [3]:
rows = 10
cols = 7
feat = 5

In [6]:
input_array = torch.randn(rows, cols)

In [7]:
input_array.size()

torch.Size([10, 7])

In [21]:
feature_array = torch.randn(cols, feat)

In [22]:
feature_array.size()

torch.Size([7, 5])

In [23]:
torch.matmul(input_array, feature_array)

tensor([[ -1.6281,  -3.0203,   0.8076,   2.6700,  -5.5953],
        [  0.6699,  -4.0461,   1.1493,   0.1548,  -3.1811],
        [ -2.5109,   3.8499,   0.4039,   2.7039,   2.1040],
        [ -1.3418,  -1.6046,   5.5940,   4.8119,  -2.2473],
        [  2.3304,  -3.4291,   1.4012,   2.0750,  -2.3476],
        [  2.8232,  -7.3698,  -1.1315,  -4.3755,  -4.2499],
        [  0.9748,   0.9203,  -1.1980,  -1.2949,   1.4815],
        [ -4.2307,  -0.4257,   5.2069,   2.5598,   0.9510],
        [ -0.2562,   2.9861, -10.1737,  -4.4543,  -0.1306],
        [ -2.1877,  -1.4023,   4.2087,   2.4879,   0.0441]])

## Dot product of 3d arrays

In [51]:
elements = 3
features = 2
observations = 100
variation = 4

In [32]:
#individual elements
element = torch.randn(elements,features)
element

tensor([[ 0.4011, -0.2666],
        [ 1.3733, -0.4354],
        [ 1.3964,  0.6583]])

In [48]:
np.random.randn(1,2)

array([[ 0.59785479, -1.19170686]])

In [41]:
data = np.array([torch.randn(elements,features).numpy() for i in range(observations)])

In [49]:
input_data = torch.tensor(data)

In [50]:
input_data.size()

torch.Size([100, 3, 2])

In [66]:
feature_3d = torch.randn(observations, features, variation)

In [67]:
feature_3d.size()

torch.Size([100, 2, 4])

In [68]:
output_3d = torch.matmul(input_data, feature_3d)

In [56]:
output_3d.size()

torch.Size([100, 3, 4])

In [69]:
input_data[0]

tensor([[ 0.8249,  1.3103],
        [ 0.5460,  1.0356],
        [ 1.0954, -0.0084]])